# Generated by Django 5.2.7 on 2025-10-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descrizione", models.TextField()),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=6)),
                ("immagine", models.ImageField(upload_to="camere/")),
            ],
        ),
        migrations.CreateModel(
            name="Prenotazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("data_checkin", models.DateField()),
                ("data_checkout", models.DateField()),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prenotazioni.camera",
                    ),
                ),
            ],
        ),
    ]
