# Generated by Django 5.2.7 on 2025-10-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prenotazioni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="tipo_struttura",
            field=models.CharField(
                choices=[("BEB", "B&B"), ("CASA", "Casa Vacanze")],
                default="BEB",
                max_length=5,
                verbose_name="Tipo di struttura",
            ),
        ),
    ]
