# Generated by Django 5.2.7 on 2025-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0002_camera_tipo_struttura'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='capienza',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
